---
title: "Second_year_ABCD_project"
output: html_document
date: "2023-10-30"
---

```{r setup markdown file, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

```{r setup, include=FALSE}

## Avoid scientific notation ----
options(scipen=999) ## forces full display of results, all digits

## clean up the environment/remove old objects ----
rm(list=ls()) 
gc()

## read in necessary libraries ----
library(dplyr)
library(tidyverse)
library(ggplot2)

## read in data ----
life_youth <- read.csv("mh_y_le.csv",header=TRUE)
cort_thick <- read.csv("mri_y_smr_thk_dsk.csv",header=TRUE)
cort_vol <- read.csv("mri_y_smr_vol_dsk.csv",header=TRUE)
subcort_vol <- read.csv("mri_y_smr_vol_aseg.csv",header=TRUE)
mri_info <- read.csv("mri_y_adm_info.csv",header=TRUE)
demo_info <- read.csv("abcd_p_demo.csv",header=TRUE)
longitudinal_info <- read.csv("abcd_y_lt.csv", header=TRUE)

## clean up youth-reported Life Events Scale data ----
#subject id, event name, total number good events, total number bad events, how much affected, and how much affected by bad events will never be NA 
life_youth <- filter(life_youth,rowSums(is.na(life_youth[,2:ncol(life_youth)]))!= ncol(life_youth)-6) 
## add columns to add dataframes for combined subject and visit ID ----
life_youth <- life_youth %>% mutate("subject_visit_id" =
                                    paste0(life_youth$src_subject_id,"__",life_youth$eventname),
                                    .after = eventname)
cort_thick <- cort_thick %>% mutate("subject_visit_id" =
                                    paste0(cort_thick$src_subject_id,"__",cort_thick$eventname),
                                    .after = eventname)
cort_vol <- cort_vol %>% mutate("subject_visit_id" =
                                    paste0(cort_vol$src_subject_id,"__",cort_vol$eventname),
                                    .after = eventname)
subcort_vol <- subcort_vol %>% mutate("subject_visit_id" =
                                    paste0(subcort_vol$src_subject_id,"__",subcort_vol$eventname),
                                    .after = eventname)
mri_info <- mri_info %>% mutate("subject_visit_id" =
                                    paste0(mri_info$src_subject_id,"__",mri_info$eventname),
                                    .after = eventname)
demo_info <- demo_info %>% mutate("subject_visit_id" =
                                    paste0(demo_info$src_subject_id,"__",demo_info$eventname),
                                    .after = eventname)
longitudinal_info <- longitudinal_info %>% mutate("subject_visit_id" =
                                    paste0(longitudinal_info$src_subject_id,"__",
                                           longitudinal_info$eventname),
                                    .after = eventname)

## create one data frame with all metadata, life events data, and structural mri data ----
df_list <- list(life_youth,cort_thick,cort_vol,subcort_vol,mri_info,demo_info,longitudinal_info)
alldata <- df_list %>% reduce(full_join, by='subject_visit_id')

## combine many columns for race into one categorical column ----
alldata <- alldata %>% 
            mutate(demo_race_all = case_when(demo_race_a_p___10 == 1 ~ "10",
                                             demo_race_a_p___11 == 1 ~ "11",
                                             demo_race_a_p___12 == 1 ~ "12",
                                             demo_race_a_p___13 == 1 ~ "13",
                                             demo_race_a_p___14 == 1 ~ "14",
                                             demo_race_a_p___15 == 1 ~ "15",
                                             demo_race_a_p___16 == 1 ~ "16",
                                             demo_race_a_p___17 == 1 ~ "17",
                                             demo_race_a_p___18 == 1 ~ "18",
                                             demo_race_a_p___19 == 1 ~ "19",
                                             demo_race_a_p___20 == 1 ~ "20",
                                             demo_race_a_p___21 == 1 ~ "21", 
                                             demo_race_a_p___22 == 1 ~ "22",
                                             demo_race_a_p___23 == 1 ~ "23",
                                             demo_race_a_p___24 == 1 ~ "24",
                                             demo_race_a_p___25 == 1 ~ "25",
                                             demo_race_a_p___77 == 1 ~ "77",
                                             demo_race_a_p___99 == 1 ~ "99",
                                             ),
                    .after=demo_race_a_p___10)
```

```{r feasibility testing, include=FALSE}

## feasibility based only on Life Events Scale ----
# number of unique subjects with at least one time point
length(unique(life_youth$src_subject_id))
# note: Life Events Scale was not administered during baseline visit
# number of unique subjects with data from year 1
length(unique(life_youth$src_subject_id[which(life_youth$eventname=="1_year_follow_up_y_arm_1")]))
# number of unique subjects with data from year 2
length(unique(life_youth$src_subject_id[which(life_youth$eventname=="2_year_follow_up_y_arm_1")]))
# number of unique subjects with data from year 3
length(unique(life_youth$src_subject_id[which(life_youth$eventname=="3_year_follow_up_y_arm_1")]))
# number of unique subjects with data from year 4
length(unique(life_youth$src_subject_id[which(life_youth$eventname=="4_year_follow_up_y_arm_1")]))

## feasibility based on Life Events Scale and cortical thickness----
length(unique(cort_thick$src_subject_id) %in% unique(life_youth$src_subject_id))

## feasibility based on Life Events Scale and cortical volume----
length(unique(cort_vol$src_subject_id) %in% unique(life_youth$src_subject_id))

## feasibility based on Life Events Scale and subcortical volume----
length(unique(subcort_vol$src_subject_id) %in% unique(life_youth$src_subject_id))

```

```{r variables to include, include=FALSE}

## fixed metadata and mri variables to account for ----
demo_info$demo_sex_v2 #child's sex assigned at birth
demo_info$demo_race_all #child's race as defined by parents
demo_info$acs_raked_propensity_score #propensity score to weight based on demographic and SES using results of American Community Survey
longitudinal_info$interview_age #age in months at time of visit

## random metadata and mri variables to account for ----
longitudinal_info$rel_family_id #family id
longitudinal_info$school_id #school id
longitudinal_info$district_id #district id
longitudinal_info$site_id_l #site id
subcort_vol$smri_vol_scs_wholeb # total subcortical volume (for subcortical volume measures)
cort_vol$smri_vol_cdk_total # total cortical volume (for cortical volume measures)
cort_thick$smri_thick_cdk_mean # average cortical thickness (for cortical thickness measures)
mri_info$mri_info_manufacturer # mri scanner manufacturer

## behavioral measures ----
cbcl_scr_syn_aggressive_t # CBCL aggression subscale t-score
cbcl_scr_syn_anxdep_t # CBCL anxiety/depression subscale t-score
cbcl_scr_syn_attention_t # CBCL attention subscale t-score
cbcl_scr_syn_external_t # CBCL externalizing subscale (rule-breaking, aggressive) t-score
cbcl_scr_syn_internal_t # CBCL internalizing subscale (withdrawn/depressed, somatic, anxiety/depression) t-score
cbcl_scr_syn_rulebreak_t # CBCL rule-breaking subscale t-score
cbcl_scr_syn_social_t # CBCL social subscale t-score
cbcl_scr_syn_somatic_t # CBCL somatic subscale t-score
cbcl_scr_syn_thought_t # CBCL thought syndrome subscale t-score
cbcl_scr_syn_totprob_t # CBCL total problems (externalizing, internalizing, thought, attention) t-score
cbcl_scr_syn_withdep_t # CBCL withdrawn/depressed t-score

## child-reported and caregiver-reported life events ----






```