---
title: "Stress-related PRS"
output: html_document
date: "2024-02-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Import data, load libraries

```{r import data, load libraries, echo=FALSE}

### load libraries ####
library(readxl)

### import data ####

## ABCD data
demo <- read.csv("abcd_p_demo.csv",header=T) # demographics
meta <- read.csv("abcd_y_lt.csv",header=T) #site id, interview age
cbcl <- read.csv("mh_p_cbcl.csv",header=T) # cbcl

## PRS
prs_no_mhc <- read.table("StressPRS.profile",header=T) #not including any snps in mhc
prs_one_mhc <- read.table("StressPRS_w_MHC.profile",header=T) #including one snp in mhc w highest effect size
prs_all_mhc <- read.table("StressPRS_w_one_MHC.profile",header=T) #include all snps in mhc

## genetic relatedness matrices (GRMs)
all_grm <- readRDS(file = "ABCD_All_PCRel_grm_sparse.rda") # all ancestries
afr_grm <- readRDS(file = "ABCD_Afr_PCRel_grm_sparse.rda") # african ancestry
amadmix_grm <- readRDS(file = "ABCD_AmerAdmix_PCRel_grm_sparse.rda") # american admixed ancestry
eur_grm <- readRDS(file = "ABCD_Eur_PCRel_grm_sparse.rda") # european ancestry

## ancestry groupings
afr_gp <- read_xlsx("ABCD_RF_Afr_Grouping.xlsx")
amadmix_gp <- read_xlsx("ABCD_RF_AmerAdmix_Grouping.xlsx")
eur_gp <- read_xlsx("ABCD_RF_Eur_Grouping.xlsx")

```

### Group all like files into one data frame each

```{r group data, echo=FALSE}

abcd_all <- demo %>%
              select(c("src_subject_id","eventname",
                       "demo_sex_v2","demo_gender_id_v2","demo_gender_id_v2_l",
                       "demo_comb_income_v2","demo_comb_income_v2_l")) %>%
              left_join(select(meta,
                               c("src_subject_id","eventname","interview_age")),
                        by=c("src_subject_id","eventname")) %>%
              left_join(select(cbcl,
                               c("src_subject_id","eventname",
                                 "cbcl_scr_syn_aggressive_t","cbcl_scr_syn_attention_t",
                                 "cbcl_scr_syn_anxdep_t","cbcl_scr_syn_external_t",
                                 "cbcl_scr_syn_internal_t","cbcl_scr_syn_rulebreak_t",
                                 "cbcl_scr_syn_social_t","cbcl_scr_syn_somatic_t",
                                 "cbcl_scr_syn_thought_t","cbcl_scr_syn_totprob_t",
                                 "cbcl_scr_syn_withdep_t")),
                        by=c("src_subject_id","eventname"))

prs_all <- prs_all_mhc %>%
              left_join(select(prs_one_mhc,c("SCORESUM","IID")),
                        by="IID") %>%
              rename(prs_all_mhc_val = SCORESUM.x,
                     prs_one_mhc_val = SCORESUM.y) %>%
              left_join(select(prs_no_mhc,c("SCORESUM","IID")),
                        by="IID") %>%
              rename(prs_no_mhc_val = SCORESUM) %>%
              select(c("IID","prs_all_mhc_val","prs_one_mhc_val","prs_no_mhc_val")) %>%
              rename(src_subject_id = IID)
prs_all$src_subject_id <- gsub("^.{1,10}","",prs_all$src_subject_id) #if remove first 10 char then = subject id as in abcd

afr_gp <- afr_gp %>% mutate(ancestry="Afr")
amadmix_gp <- amadmix_gp %>% mutate(ancestry="AmAdmix")
eur_gp <- eur_gp %>% mutate(ancestry="Eur")
ancestry_gp_all <- bind_rows(afr_gp,amadmix_gp,eur_gp) %>%
                      select("subjectkey","ancestry","V1","V2","V3","V4","V5","V6","V7","V8") %>%
                      rename(src_subject_id = subjectkey)

```

### Separate data based on collection date

``` {r}
baseline_data <- abcd_all %>%
                    filter(eventname == "baseline_year_1_arm_1") %>% #keep all data from baseline only
                    right_join(prs_all,by="src_subject_id") %>% #keep all rows from PRS, remove abcd rows not in PRS
                    right_join(ancestry_gp_all,by="src_subject_id") #keep all rows from ancestry, remove other rows not in ancestry

yr1_data <- abcd_all %>%
                    filter(eventname == "1_year_follow_up_y_arm_1") %>% #keep all data from year 1 follow-up only
                    right_join(prs_all,by="src_subject_id") %>% #keep all rows from PRS, remove abcd rows not in PRS
                    right_join(ancestry_gp_all,by="src_subject_id") #keep all rows from ancestry, remove other rows not in ancestry

yr2_data <- abcd_all %>%
                    filter(eventname == "2_year_follow_up_y_arm_1") %>% #keep all data from year 2 follow-up only
                    right_join(prs_all,by="src_subject_id") %>% #keep all rows from PRS, remove abcd rows not in PRS
                    right_join(ancestry_gp_all,by="src_subject_id") #keep all rows from ancestry, remove other rows not in ancestry

yr3_data <- abcd_all %>%
                    filter(eventname == "3_year_follow_up_y_arm_1") %>% #keep all data from year 3 follow-up only
                    right_join(prs_all,by="src_subject_id") %>% #keep all rows from PRS, remove abcd rows not in PRS
                    right_join(ancestry_gp_all,by="src_subject_id") #keep all rows from ancestry, remove other rows not in ancestry

yr4_data <- abcd_all %>%
                    filter(eventname == "4_year_follow_up_y_arm_1") %>% #keep all data from year 4 follow-up only
                    right_join(prs_all,by="src_subject_id") %>% #keep all rows from PRS, remove abcd rows not in PRS
                    right_join(ancestry_gp_all,by="src_subject_id") #keep all rows from ancestry, remove other rows not in ancestry
```

### Reorder data so matches grm

```{r}

### All ancestries
rownames(all_grm) <- gsub("^.{1,10}","",rownames(all_grm)) #if remove first 10 char from rownames in grm then = subject id
colnames(all_grm) <- gsub("^.{1,10}","",colnames(all_grm)) #if remove first 10 char from rownames in grm then = subject id
                    
row_indices_All <- match(baseline_data$src_subject_id,rownames(all_grm)) 
all_grm_sparse_subsetted <- all_grm[row_indices_All, row_indices_All]
baseline_data_reordered <- baseline_data[match(colnames(all_grm_sparse_subsetted),baseline_data$src_subject_id),]
rownames(baseline_data_reordered) <- baseline_data$src_subject_id
# all_grm_sparse_subsetted_mat <- as.matrix(all_grm_sparse_subsetted) %>% as.data.frame # For easy viewing

### African ancestry
rownames(afr_grm) <- gsub("^.{1,10}","",rownames(afr_grm)) #if remove first 10 char from rownames in grm then = subject id
colnames(afr_grm) <- gsub("^.{1,10}","",colnames(afr_grm)) #if remove first 10 char from rownames in grm then = subject id

afr_baseline_data <- baseline_data %>% filter(ancestry=="Afr")
row_indices_All <- match(afr_baseline_data$src_subject_id,rownames(afr_grm))
afr_grm_sparse_subsetted <- afr_grm[row_indices_All, row_indices_All]
afr_baseline_data_reordered <- afr_baseline_data[match(colnames(afr_grm_sparse_subsetted),afr_baseline_data$src_subject_id),]
rownames(afr_baseline_data_reordered) <- afr_baseline_data$src_subject_id
# afr_grm_sparse_subsetted_mat <- as.matrix(afr_grm_sparse_subsetted) %>% as.data.frame # For easy viewing

### American admixed ancestry
rownames(amadmix_grm) <- gsub("^.{1,10}","",rownames(amadmix_grm)) #if remove first 10 char from rownames in grm then = subject id
colnames(amadmix_grm) <- gsub("^.{1,10}","",colnames(amadmix_grm)) #if remove first 10 char from rownames in grm then = subject id
amadmix_baseline_data <- baseline_data %>% filter(ancestry=="AmAdmix")

row_indices_All <- match(amadmix_baseline_data$src_subject_id,rownames(amadmix_grm))
amadmix_grm_sparse_subsetted <- amadmix_grm[row_indices_All, row_indices_All]
amadmix_baseline_data_reordered <- amadmix_baseline_data[match(colnames(amadmix_grm_sparse_subsetted),
                                                               amadmix_baseline_data$src_subject_id),]
rownames(amadmix_baseline_data_reordered) <- amadmix_baseline_data$src_subject_id

### European ancestry
rownames(eur_grm) <- gsub("^.{1,10}","",rownames(eur_grm)) #if remove first 10 char from rownames in grm then = subject id
colnames(eur_grm) <- gsub("^.{1,10}","",colnames(eur_grm)) #if remove first 10 char from rownames in grm then = subject id

eur_baseline_data <- baseline_data %>% filter(ancestry=="Eur")

row_indices_All <- match(eur_baseline_data$src_subject_id,rownames(eur_grm))
eur_grm_sparse_subsetted <- eur_grm[row_indices_All, row_indices_All]
eur_baseline_data_reordered <- eur_baseline_data[match(colnames(eur_grm_sparse_subsetted),
                                                       eur_baseline_data$src_subject_id),]
rownames(eur_baseline_data_reordered) <- eur_baseline_data$src_subject_id

```

### Run regressions for all CBCL outcomes at baseline

``` {r}

outcome_list <- c("cbcl_scr_syn_aggressive_t","cbcl_scr_syn_attention_t",
                  "cbcl_scr_syn_anxdep_t","cbcl_scr_syn_external_t",
                  "cbcl_scr_syn_internal_t","cbcl_scr_syn_rulebreak_t",
                  "cbcl_scr_syn_social_t","cbcl_scr_syn_somatic_t",
                  "cbcl_scr_syn_thought_t","cbcl_scr_syn_totprob_t",
                  "cbcl_scr_syn_withdep_t" )

### All ancestries ####
lm_all_grm_all_mhc_results <- list() # initialize a list to store results for prs with all mhc snps
lm_all_grm_one_mhc_results <- list() # initialize a list to store results for prs with one mhc snp
lm_all_grm_no_mhc_results <- list() # initialize a list to store results for prs with no mhc snps

for (outcome in outcome_list) {
  # Fit null models
  lm_all_grm_all_mhc_model <- fitNullModel(baseline_data_reordered, 
                           outcome = outcome, 
                           covars = c("prs_all_mhc_val","interview_age",
                                      "demo_sex_v2",
                                      # "demo_comb_income_v2",
                                      paste0("V", 1:8)), 
                           cov.mat = all_grm_sparse_subsetted, 
                           verbose = TRUE)
  lm_all_grm_one_mhc_model <- fitNullModel(baseline_data_reordered, 
                           outcome = outcome, 
                           covars = c("prs_one_mhc_val","interview_age",
                                      "demo_sex_v2",
                                      # "demo_comb_income_v2",
                                      paste0("V", 1:8)), 
                           cov.mat = all_grm_sparse_subsetted, 
                           verbose = TRUE)
  lm_all_grm_no_mhc_model <- fitNullModel(baseline_data_reordered, 
                           outcome = outcome, 
                           covars = c("prs_no_mhc_val","interview_age",
                                      "demo_sex_v2",
                                      # "demo_comb_income_v2",
                                      paste0("V", 1:8)), 
                           cov.mat = all_grm_sparse_subsetted, 
                           verbose = TRUE)
  
  # Store the fixef component
  lm_all_grm_all_mhc_results[[outcome]] <- lm_all_mhc_model$fixef
  lm_all_grm_one_mhc_results[[outcome]] <- lm_one_mhc_model$fixef
  lm_all_grm_no_mhc_results[[outcome]] <- lm_no_mhc_model$fixef
}


### African ancestry ####
lm_afr_grm_all_mhc_results <- list() # initialize a list to store results for prs with all mhc snps
lm_afr_grm_one_mhc_results <- list() # initialize a list to store results for prs with one mhc snp
lm_afr_grm_no_mhc_results <- list() # initialize a list to store results for prs with no mhc snps

for (outcome in outcome_list) {
  # Fit null models
  lm_afr_grm_all_mhc_model <- fitNullModel(afr_baseline_data_reordered, 
                           outcome = outcome, 
                           covars = c("prs_all_mhc_val","interview_age",
                                      "demo_sex_v2",
                                      # "demo_comb_income_v2",
                                      paste0("V", 1:8)), 
                           cov.mat = afr_grm_sparse_subsetted, 
                           verbose = TRUE)
  lm_afr_grm_one_mhc_model <- fitNullModel(afr_baseline_data_reordered, 
                           outcome = outcome, 
                           covars = c("prs_one_mhc_val","interview_age",
                                      "demo_sex_v2",
                                      # "demo_comb_income_v2",
                                      paste0("V", 1:8)), 
                           cov.mat = afr_grm_sparse_subsetted, 
                           verbose = TRUE)
  lm_afr_grm_no_mhc_model <- fitNullModel(afr_baseline_data_reordered, 
                           outcome = outcome, 
                           covars = c("prs_no_mhc_val","interview_age",
                                      "demo_sex_v2",
                                      # "demo_comb_income_v2",
                                      paste0("V", 1:8)), 
                           cov.mat = afr_grm_sparse_subsetted, 
                           verbose = TRUE)
  
  # Store the fixef component
  lm_afr_grm_all_mhc_results[[outcome]] <- lm_all_mhc_model$fixef
  lm_afr_grm_one_mhc_results[[outcome]] <- lm_one_mhc_model$fixef
  lm_afr_grm_no_mhc_results[[outcome]] <- lm_no_mhc_model$fixef
}

### American admixed ancestries ####
lm_amadmix_grm_all_mhc_results <- list() # initialize a list to store results for prs with all mhc snps
lm_amadmix_grm_one_mhc_results <- list() # initialize a list to store results for prs with one mhc snp
lm_amadmix_grm_no_mhc_results <- list() # initialize a list to store results for prs with no mhc snps

for (outcome in outcome_list) {
  # Fit null models
  lm_amadmix_grm_all_mhc_model <- fitNullModel(amadmix_baseline_data_reordered, 
                           outcome = outcome, 
                           covars = c("prs_all_mhc_val","interview_age",
                                      "demo_sex_v2",
                                      # "demo_comb_income_v2",
                                      paste0("V", 1:8)), 
                           cov.mat = amadmix_grm_sparse_subsetted, 
                           verbose = TRUE)
  lm_amadmix_grm_one_mhc_model <- fitNullModel(amadmix_baseline_data_reordered, 
                           outcome = outcome, 
                           covars = c("prs_one_mhc_val","interview_age",
                                      "demo_sex_v2",
                                      # "demo_comb_income_v2",
                                      paste0("V", 1:8)), 
                           cov.mat = amadmix_grm_sparse_subsetted, 
                           verbose = TRUE)
  lm_amadmix_grm_no_mhc_model <- fitNullModel(amadmix_baseline_data_reordered, 
                           outcome = outcome, 
                           covars = c("prs_no_mhc_val","interview_age",
                                      "demo_sex_v2",
                                      # "demo_comb_income_v2",
                                      paste0("V", 1:8)), 
                           cov.mat = amadmix_grm_sparse_subsetted, 
                           verbose = TRUE)
  
  # Store the fixef component
  lm_amadmix_grm_all_mhc_results[[outcome]] <- lm_all_mhc_model$fixef
  lm_amadmix_grm_one_mhc_results[[outcome]] <- lm_one_mhc_model$fixef
  lm_amadmix_grm_no_mhc_results[[outcome]] <- lm_no_mhc_model$fixef
}

### European ancestry ####
lm_eur_grm_all_mhc_results <- list() # initialize a list to store results for prs with all mhc snps
lm_eur_grm_one_mhc_results <- list() # initialize a list to store results for prs with one mhc snp
lm_eur_grm_no_mhc_results <- list() # initialize a list to store results for prs with no mhc snps

for (outcome in outcome_list) {
  # Fit null models
  lm_eur_grm_all_mhc_model <- fitNullModel(eur_baseline_data_reordered, 
                           outcome = outcome, 
                           covars = c("prs_all_mhc_val","interview_age",
                                      "demo_sex_v2",
                                      # "demo_comb_income_v2",
                                      paste0("V", 1:8)), 
                           cov.mat = eur_grm_sparse_subsetted, 
                           verbose = TRUE)
  lm_eur_grm_one_mhc_model <- fitNullModel(eur_baseline_data_reordered, 
                           outcome = outcome, 
                           covars = c("prs_one_mhc_val","interview_age",
                                      "demo_sex_v2",
                                      # "demo_comb_income_v2",
                                      paste0("V", 1:8)), 
                           cov.mat = eur_grm_sparse_subsetted, 
                           verbose = TRUE)
  lm_eur_grm_no_mhc_model <- fitNullModel(eur_baseline_data_reordered, 
                           outcome = outcome, 
                           covars = c("prs_no_mhc_val","interview_age",
                                      "demo_sex_v2",
                                      # "demo_comb_income_v2",
                                      paste0("V", 1:8)), 
                           cov.mat = eur_grm_sparse_subsetted, 
                           verbose = TRUE)
  
  # Store the fixef component
  lm_eur_grm_all_mhc_results[[outcome]] <- lm_all_mhc_model$fixef
  lm_eur_grm_one_mhc_results[[outcome]] <- lm_one_mhc_model$fixef
  lm_eur_grm_no_mhc_results[[outcome]] <- lm_no_mhc_model$fixef
}

```