---
title: "Stress-related PRS"
output: html_document
date: "2024-02-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("C:/Users/Kate Scheuer/OneDrive - UW/Desktop/Lab/Second_year_ABCD_project/Working")

```

### Import data, load libraries

```{r import data, load libraries, echo=FALSE}

### load libraries ####
library(readxl)
library(tidyverse)
library(GENESIS)
library(lme4)
library(Matrix)
library(misty)
library(lmerTest)

### avoid scientific notation ####
options(scipen=999) ## forces full display of results, all digits
# to change it back to scientific notation, use: options(scipen=0)


### import data ####

## ABCD data
demo <- read.csv("abcd_p_demo.csv",header=T) # demographics
# income <- read_xlsx("ABCD_SES_incomeneeds.xlsx")
meta <- read.csv("abcd_y_lt.csv",header=T) #site id, interview age
cbcl <- read.csv("mh_p_cbcl.csv",header=T) # cbcl
ksads_y <- read.csv("mh_y_ksads_ss.csv",header=T) #youth-reported ksads
ksads_p <- read.csv("mh_p_ksads_ss.csv",header=T) #parent-reported ksads

## federal poverty data from https://aspe.hhs.gov/topics/poverty-economic-mobility/poverty-guidelines
poverty_info <- read.csv("federal_poverty_info.csv",header=T)

## PRS 
prs_no_mhc <- read.table("StressPRS.profile",header=T) #not including any snps in mhc
prs_one_mhc <- read.table("StressPRS_w_MHC.profile",header=T) #including one snp in mhc w highest effect size
prs_all_mhc <- read.table("StressPRS_w_one_MHC.profile",header=T) #include all snps in mhc

## genetic relatedness matrices (GRMs)
all_grm <- readRDS(file = "ABCD_All_PCRel_grm_sparse.rda") # all ancestries
afr_grm <- readRDS(file = "ABCD_Afr_PCRel_grm_sparse.rda") # african ancestry
amadmix_grm <- readRDS(file = "ABCD_AmerAdmix_PCRel_grm_sparse.rda") # american admixed ancestry
eur_grm <- readRDS(file = "ABCD_Eur_PCRel_grm_sparse.rda") # european ancestry

## ancestry groupings
afr_gp <- read_xlsx("ABCD_RF_Afr_Grouping.xlsx")
amadmix_gp <- read_xlsx("ABCD_RF_AmerAdmix_Grouping.xlsx")
eur_gp <- read_xlsx("ABCD_RF_Eur_Grouping.xlsx")

```

### Group all like files into one data frame each, basic data cleaning

```{r group data, echo=FALSE}

### make one column each for ever having ksads diagnosis ####
ksads <- select(ksads_y,c("src_subject_id","eventname",
                          
                         "ksads_14_854_t", # past adhd baseline to year 2
                         "ksads2_14_810_t", # past adhd year 3+
                         "ksads_14_853_t", # current adhd baseline to year 2
                         "ksads2_14_809_t", # current adhd year 3+
                         "ksads2_14_812_t", # full remission adhd year 3+
                         "ksads_14_855_t", # partial remission adhd baseline to year 2
                         "ksads2_14_811_t", # partial remission adhd year 3+
                         "ksads2_14_813_t", # other adhd year 3+
                         "ksads_14_856_t", # unspecified adhd baseline to year 2
                         
                         "ksads2_10_828_t", # past gad year 3+
                         "ksads2_10_827_t", # current gad year 3+
                         "ksads_10_870_t", # past gad baseline to year 2
                         "ksads_10_869_t", # current gad baseline to year 2
                         "ksads_10_913_t", # gad < min duration baseline to year 2
                         "ksads2_10_873_t", # gad < min duration year 3+
                         "ksads_10_914_t", # past gad < min duration baseline to year 2
                         "ksads2_10_874_t", # past gad < min duration year 3+
                         
                         "ksads_1_840_t", # current mdd baseline to year 2
                         "ksads2_1_790_t", # current mdd year 3+
                         "ksads_1_841_t", # partial remission mdd baseline to year 2
                         "ksads2_1_791_t", # partial remission mdd year 3+
                         "ksads_1_842_t", # past mdd baseline to year 2
                         "ksads2_1_792_t", # past mdd year 3+
                         
                         "ksads_21_922_t", # past ptsd baseline to year 2
                         "ksads2_21_883_t", # past ptsd year 3+
                         "ksads_21_921_t", # current ptsd baseline to year 2
                         "ksads2_21_881_t", # current ptsd year 3+
                         "ksads2_21_882_t" # partial remission ptsd year 3+
                         )) %>%
        left_join(
          select(ksads_p,c("src_subject_id","eventname",
                            "ksads_14_855_p", # partial remission adhd baseline to year 2
                            "ksads_14_854_p", # past adhd baseline to year 2
                            "ksads2_14_810_p", # past adhd year 3+
                            "ksads_14_853_p", # current adhd baseline to year 2
                            "ksads2_14_809_p", # currend adhd year 3+
                            "ksads2_14_812_p", # full remission adhd year 3+ 
                            "ksads2_14_811_p", # partial remission adhd year 3+ 
                            "ksads2_14_813_p", # other adhd year 3+ 
                            "ksads_14_856_p", # unspecified adhd baseline to year 2
                           
                            "ksads2_10_828_p", # past gad year 3+
                            "ksads2_10_827_p", # currend gad year 3+
                            "ksads_10_870_p", # past gad baseline to year 2
                            "ksads_10_869_p", # current gad baseline to year 2
                            "ksads_10_913_p", # gad < min duration baseline to year 2
                            "ksads_10_914_p", # past gad < min duration baseline to year 2
                            "ksads2_10_873_p", # gad < min duration year 3+
                            "ksads2_10_874_p", # past gad < min duration year 3+
                           
                            "ksads_1_841_p", # partial remission mdd baseline to year 2
                            "ksads_1_842_p", # past mdd baseline to year 2
                            "ksads_1_840_p", # current mdd baseline to year 2
                            "ksads2_1_790_p", # current mdd year 3+
                            "ksads2_1_791_p", # partial remission mdd year 3+
                            "ksads2_1_792_p", # past mdd year 3+
                           
                            "ksads_21_922_p", # past ptsd baseline to year 2
                            "ksads2_21_883_p", # past ptsd year 3+
                            "ksads_21_921_p", # current ptsd baseline to year 2
                            "ksads2_21_881_p", # current ptsd year 3+
                            "ksads2_21_882_p" # partial remission ptsd year 3+
                            )),
                  by=c("src_subject_id","eventname")) %>%
              mutate(adhd = case_when(
                                      ksads_14_854_t == 1 ~ 1,
                                      ksads_14_854_t == 0 ~ 0,
                                      ksads_14_854_t == 555 ~ NA,
                                      ksads_14_854_t == 888 ~ NA,
                                      ksads_14_854_t == NA ~ NA,
                                      
                                      ksads2_14_810_t == 1 ~ 1,
                                      ksads2_14_810_t == 0 ~ 0,
                                      ksads2_14_810_t == 555 ~ NA,
                                      ksads2_14_810_t == 888 ~ NA,
                                      ksads2_14_810_t == NA ~ NA,
                                      
                                      ksads_14_853_t == 1 ~ 1,
                                      ksads_14_853_t == 0 ~ 0,
                                      ksads_14_853_t == 555 ~ NA,
                                      ksads_14_853_t == 888 ~ NA,
                                      ksads_14_853_t == NA ~ NA,
                                      
                                      ksads2_14_809_t == 1 ~ 1,
                                      ksads2_14_809_t == 0 ~ 0,
                                      ksads2_14_809_t == 555 ~ NA,
                                      ksads2_14_809_t == 888 ~ NA,
                                      ksads2_14_809_t == NA ~ NA,
                                      
                                      ksads2_14_812_t == 1 ~ 1,
                                      ksads2_14_812_t == 0 ~ 0,
                                      ksads2_14_812_t == 555 ~ NA,
                                      ksads2_14_812_t == 888 ~ NA,
                                      ksads2_14_812_t == NA ~ NA,
                                      
                                      ksads_14_855_t == 1 ~ 1,
                                      ksads_14_855_t == 0 ~ 0,
                                      ksads_14_855_t == 555 ~ NA,
                                      ksads_14_855_t == 888 ~ NA,
                                      ksads_14_855_t == NA ~ NA,
                                      
                                      ksads2_14_811_t == 1 ~ 1,
                                      ksads2_14_811_t == 0 ~ 0,
                                      ksads2_14_811_t == 555 ~ NA,
                                      ksads2_14_811_t == 888 ~ NA,
                                      ksads2_14_811_t == NA ~ NA,
                                    
                                      ksads2_14_813_t == 1 ~ 1,
                                      ksads2_14_813_t == 0 ~ 0,
                                      ksads2_14_813_t == 555 ~ NA,
                                      ksads2_14_813_t == 888 ~ NA,
                                      ksads2_14_813_t == NA ~ NA,
                                      
                                      ksads_14_856_t == 1 ~ 1,
                                      ksads_14_856_t == 0 ~ 0,
                                      ksads_14_856_t == 555 ~ NA,
                                      ksads_14_856_t == 888 ~ NA,
                                      ksads_14_856_t == NA ~ NA,
                                      
                                      ksads_14_855_p == 1 ~ 1,
                                      ksads_14_855_p == 0 ~ 0,
                                      ksads_14_855_p == 555 ~ NA,
                                      ksads_14_855_p == 888 ~ NA,
                                      ksads_14_855_p == NA ~ NA,
                                      
                                      ksads_14_854_p == 1 ~ 1,
                                      ksads_14_854_p == 0 ~ 0,
                                      ksads_14_854_p == 555 ~ NA,
                                      ksads_14_854_p == 888 ~ NA,
                                      ksads_14_854_p == NA ~ NA,
                                      
                                      ksads2_14_810_p == 1 ~ 1,
                                      ksads2_14_810_p == 0 ~ 0,
                                      ksads2_14_810_p == 555 ~ NA,
                                      ksads2_14_810_p == 888 ~ NA,
                                      ksads2_14_810_p == NA ~ NA,
                                      
                                      ksads_14_853_p == 1 ~ 1,
                                      ksads_14_853_p == 0 ~ 0,
                                      ksads_14_853_p == 555 ~ NA,
                                      ksads_14_853_p == 888 ~ NA,
                                      ksads_14_853_p == NA ~ NA,
                                      
                                      ksads2_14_809_p == 1 ~ 1,
                                      ksads2_14_809_p == 0 ~ 0,
                                      ksads2_14_809_p == 555 ~ NA,
                                      ksads2_14_809_p == 888 ~ NA,
                                      ksads2_14_809_p == NA ~ NA,
                                      
                                      ksads2_14_812_p == 1 ~ 1,
                                      ksads2_14_812_p == 0 ~ 0,
                                      ksads2_14_812_p == 555 ~ NA,
                                      ksads2_14_812_p == 888 ~ NA,
                                      ksads2_14_812_p == NA ~ NA,
                                      
                                      ksads2_14_811_p == 1 ~ 1,
                                      ksads2_14_811_p == 0 ~ 0,
                                      ksads2_14_811_p == 555 ~ NA,
                                      ksads2_14_811_p == 888 ~ NA,
                                      ksads2_14_811_p == NA ~ NA,
                                      
                                      ksads2_14_813_p == 1 ~ 1,
                                      ksads2_14_813_p == 0 ~ 0,
                                      ksads2_14_813_p == 555 ~ NA,
                                      ksads2_14_813_p == 888 ~ NA,
                                      ksads2_14_813_p == NA ~ NA,
                                      
                                      ksads_14_856_p == 1 ~ 1,
                                      ksads_14_856_p == 0 ~ 0,
                                      ksads_14_856_p == 555 ~ NA,
                                      ksads_14_856_p == 888 ~ NA,
                                      ksads_14_856_p == NA ~ NA
                                      )) %>%
              mutate(gad = case_when(
                                     ksads2_10_828_t == 1 ~ 1,
                                     ksads2_10_828_t == 0 ~ 0,
                                     ksads2_10_828_t == 555 ~ NA,
                                     ksads2_10_828_t == 888 ~ NA,
                                     ksads2_10_828_t == NA ~ NA,
                                     
                                     ksads2_10_827_t == 1 ~ 1,
                                     ksads2_10_827_t == 0 ~ 0,
                                     ksads2_10_827_t == 555 ~ NA,
                                     ksads2_10_827_t == 888 ~ NA,
                                     ksads2_10_827_t == NA ~ NA,
                                     
                                     ksads_10_870_t == 1 ~ 1,
                                     ksads_10_870_t == 0 ~ 0,
                                     ksads_10_870_t == 555 ~ NA,
                                     ksads_10_870_t == 888 ~ NA,
                                     ksads_10_870_t == NA ~ NA,
                                     
                                     ksads_10_869_t == 1 ~ 1,
                                     ksads_10_869_t == 0 ~ 0,
                                     ksads_10_869_t == 555 ~ NA,
                                     ksads_10_869_t == 888 ~ NA,
                                     ksads_10_869_t == NA ~ NA,
                                     
                                     ksads_10_913_t == 1 ~ 1,
                                     ksads_10_913_t == 0 ~ 0,
                                     ksads_10_913_t == 555 ~ NA,
                                     ksads_10_913_t == 888 ~ NA,
                                     ksads_10_913_t == NA ~ NA,
                                     
                                     ksads2_10_873_t == 1 ~ 1,
                                     ksads2_10_873_t == 0 ~ 0,
                                     ksads2_10_873_t == 555 ~ NA,
                                     ksads2_10_873_t == 888 ~ NA,
                                     ksads2_10_873_t == NA ~ NA,
                                     
                                     ksads_10_914_t == 1 ~ 1,
                                     ksads_10_914_t == 0 ~ 0,
                                     ksads_10_914_t == 555 ~ NA,
                                     ksads_10_914_t == 888 ~ NA,
                                     ksads_10_914_t == NA ~ NA,
                                     
                                     ksads2_10_874_t == 1 ~ 1,
                                     ksads2_10_874_t == 0 ~ 0,
                                     ksads2_10_874_t == 555 ~ NA,
                                     ksads2_10_874_t == 888 ~ NA,
                                     ksads2_10_874_t == NA ~ NA,
                                     
                                     ksads2_10_828_p == 1 ~ 1,
                                     ksads2_10_828_p == 0 ~ 0,
                                     ksads2_10_828_p == 555 ~ NA,
                                     ksads2_10_828_p == 888 ~ NA,
                                     ksads2_10_828_p == NA ~ NA,
                                     
                                     ksads2_10_827_p == 1 ~ 1,
                                     ksads2_10_827_p == 0 ~ 0,
                                     ksads2_10_827_p == 555 ~ NA,
                                     ksads2_10_827_p == 888 ~ NA,
                                     ksads2_10_827_p == NA ~ NA,
                                     
                                     ksads_10_870_p == 1 ~ 1,
                                     ksads_10_870_p == 0 ~ 0,
                                     ksads_10_870_p == 555 ~ NA,
                                     ksads_10_870_p == 888 ~ NA,
                                     ksads_10_870_p == NA ~ NA,
                                     
                                     ksads_10_869_p == 1 ~ 1,
                                     ksads_10_869_p == 0 ~ 0,
                                     ksads_10_869_p == 555 ~ NA,
                                     ksads_10_869_p == 888 ~ NA,
                                     ksads_10_869_p == NA ~ NA,
                                     
                                     ksads_10_913_p == 1 ~ 1,
                                     ksads_10_913_p == 0 ~ 0,
                                     ksads_10_913_p == 555 ~ NA,
                                     ksads_10_913_p == 888 ~ NA,
                                     ksads_10_913_p == NA ~ NA,
                                     
                                     ksads_10_914_p == 1 ~ 1,
                                     ksads_10_914_p == 0 ~ 0,
                                     ksads_10_914_p == 555 ~ NA,
                                     ksads_10_914_p == 888 ~ NA,
                                     ksads_10_914_p == NA ~ NA,
                                     
                                     ksads2_10_873_p == 1 ~ 1,
                                     ksads2_10_873_p == 0 ~ 0,
                                     ksads2_10_873_p == 555 ~ NA,
                                     ksads2_10_873_p == 888 ~ NA,
                                     ksads2_10_873_p == NA ~ NA,
                                     
                                     ksads2_10_874_p == 1 ~ 1,
                                     ksads2_10_874_p == 0 ~ 0,
                                     ksads2_10_874_p == 555 ~ NA,
                                     ksads2_10_874_p == 888 ~ NA,
                                     ksads2_10_874_p == NA ~ NA,
                                     )) %>%
              mutate(mdd = case_when(
                                     ksads_1_840_t == 1 ~ 1,
                                     ksads_1_840_t == 0 ~ 0,
                                     ksads_1_840_t == 555 ~ NA,
                                     ksads_1_840_t == 888 ~ NA,
                                     ksads_1_840_t == NA ~ NA,
                                     
                                     ksads2_1_790_t == 1 ~ 1,
                                     ksads2_1_790_t == 0 ~ 0,
                                     ksads2_1_790_t == 555 ~ NA,
                                     ksads2_1_790_t == 888 ~ NA,
                                     ksads2_1_790_t == NA ~ NA,
                                     
                                     ksads_1_841_t == 1 ~ 1,
                                     ksads_1_841_t == 0 ~ 0,
                                     ksads_1_841_t == 555 ~ NA,
                                     ksads_1_841_t == 888 ~ NA,
                                     ksads_1_841_t == NA ~ NA,
                                     
                                     ksads2_1_791_t == 1 ~ 1,
                                     ksads2_1_791_t == 0 ~ 0,
                                     ksads2_1_791_t == 555 ~ NA,
                                     ksads2_1_791_t == 888 ~ NA,
                                     ksads2_1_791_t == NA ~ NA,
                                     
                                     ksads_1_842_t == 1 ~ 1,
                                     ksads_1_842_t == 0 ~ 0,
                                     ksads_1_842_t == 555 ~ NA,
                                     ksads_1_842_t == 888 ~ NA,
                                     ksads_1_842_t == NA ~ NA,
                                     
                                     ksads2_1_792_t == 1 ~ 1,
                                     ksads2_1_792_t == 0 ~ 0,
                                     ksads2_1_792_t == 555 ~ NA,
                                     ksads2_1_792_t == 888 ~ NA,
                                     ksads2_1_792_t == NA ~ NA,
                                     
                                     ksads_1_841_p == 1 ~ 1,
                                     ksads_1_841_p == 0 ~ 0,
                                     ksads_1_841_p == 555 ~ NA,
                                     ksads_1_841_p == 888 ~ NA,
                                     ksads_1_841_p == NA ~ NA,
                                     
                                     ksads_1_842_p == 1 ~ 1,
                                     ksads_1_842_p == 0 ~ 0,
                                     ksads_1_842_p == 555 ~ NA,
                                     ksads_1_842_p == 888 ~ NA,
                                     ksads_1_842_p == NA ~ NA,
                                     
                                     ksads_1_840_p == 1 ~ 1,
                                     ksads_1_840_p == 0 ~ 0,
                                     ksads_1_840_p == 555 ~ NA,
                                     ksads_1_840_p == 888 ~ NA,
                                     ksads_1_840_p == NA ~ NA,
                                     
                                     ksads2_1_790_p == 1 ~ 1,
                                     ksads2_1_790_p == 0 ~ 0,
                                     ksads2_1_790_p == 555 ~ NA,
                                     ksads2_1_790_p == 888 ~ NA,
                                     ksads2_1_790_p == NA ~ NA,
                                     
                                     ksads2_1_791_p == 1 ~ 1,
                                     ksads2_1_791_p == 0 ~ 0,
                                     ksads2_1_791_p == 555 ~ NA,
                                     ksads2_1_791_p == 888 ~ NA,
                                     ksads2_1_791_p == NA ~ NA,
                                     
                                     ksads2_1_792_p == 1 ~ 1,
                                     ksads2_1_792_p == 0 ~ 0,
                                     ksads2_1_792_p == 555 ~ NA,
                                     ksads2_1_792_p == 888 ~ NA,
                                     ksads2_1_792_p == NA ~ NA
                                     )) %>%
              mutate(ptsd = case_when(
                                      ksads_21_922_t == 1 ~ 1,
                                      ksads_21_922_t == 0 ~ 0,
                                      ksads_21_922_t == 555 ~ NA,
                                      ksads_21_922_t == 888 ~ NA,
                                      ksads_21_922_t == NA ~ NA,
                                      
                                      ksads2_21_883_t == 1 ~ 1,
                                      ksads2_21_883_t == 0 ~ 0,
                                      ksads2_21_883_t == 555 ~ NA,
                                      ksads2_21_883_t == 888 ~ NA,
                                      ksads2_21_883_t == NA ~ NA,
                                      
                                      ksads_21_921_t == 1 ~ 1,
                                      ksads_21_921_t == 0 ~ 0,
                                      ksads_21_921_t == 555 ~ NA,
                                      ksads_21_921_t == 888 ~ NA,
                                      ksads_21_921_t == NA ~ NA,
                                      
                                      ksads2_21_881_t == 1 ~ 1,
                                      ksads2_21_881_t == 0 ~ 0,
                                      ksads2_21_881_t == 555 ~ NA,
                                      ksads2_21_881_t == 888 ~ NA,
                                      ksads2_21_881_t == NA ~ NA,
                                      
                                      ksads2_21_882_t == 1 ~ 1,
                                      ksads2_21_882_t == 0 ~ 0,
                                      ksads2_21_882_t == 555 ~ NA,
                                      ksads2_21_882_t == 888 ~ NA,
                                      ksads2_21_882_t == NA ~ NA,
                                      
                                      ksads_21_922_p == 1 ~ 1,
                                      ksads_21_922_p == 0 ~ 0,
                                      ksads_21_922_p == 555 ~ NA,
                                      ksads_21_922_p == 888 ~ NA,
                                      ksads_21_922_p == NA ~ NA,
                                      
                                      ksads2_21_883_p == 1 ~ 1,
                                      ksads2_21_883_p == 0 ~ 0,
                                      ksads2_21_883_p == 555 ~ NA,
                                      ksads2_21_883_p == 888 ~ NA,
                                      ksads2_21_883_p == NA ~ NA,
                                      
                                      ksads_21_921_p == 1 ~ 1,
                                      ksads_21_921_p == 0 ~ 0,
                                      ksads_21_921_p == 555 ~ NA,
                                      ksads_21_921_p == 888 ~ NA,
                                      ksads_21_921_p == NA ~ NA,
                                      
                                      ksads2_21_881_p == 1 ~ 1,
                                      ksads2_21_881_p == 0 ~ 0,
                                      ksads2_21_881_p == 555 ~ NA,
                                      ksads2_21_881_p == 888 ~ NA,
                                      ksads2_21_881_p == NA ~ NA,
                                      
                                      ksads2_21_882_p == 1 ~ 1,
                                      ksads2_21_882_p == 0 ~ 0,
                                      ksads2_21_882_p == 555 ~ NA,
                                      ksads2_21_882_p == 888 ~ NA,
                                      ksads2_21_882_p == NA ~ NA
                                      )) %>%
              select(c("src_subject_id","eventname",
                       "adhd","gad","mdd","ptsd"))








### calculate income to needs ratio
income_df <- demo %>%
              select(c("src_subject_id","eventname",
                       "demo_roster_v2","demo_roster_v2_l",
                       "demo_roster_v2_refuse","demo_roster_v2_refuse_l",
                       "demo_comb_income_v2","demo_comb_income_v2_l")) %>%
              # combine items for income from baseline to yr 2 and yr 3+
              mutate(income_category = case_when(!is.na(demo_comb_income_v2) ~ demo_comb_income_v2,
                                        !is.na(demo_comb_income_v2_l) ~ demo_comb_income_v2_l
                                  )) %>%
              # for income replace 777 and 999 with NA
              mutate(income_category = ifelse(income_category %in% 
                                                c(777,999) , NA, income_category)) %>%
              # add column for middle value of income category (or upper for 10)
              mutate(income_val = case_when(income_category == 1 ~ 2499.5, # less than 5,000
                                            income_category == 2 ~ 8499.5, # 5,000 to 11,999
                                            income_category == 3 ~ 13999.5, # 12,000 to 15,999
                                            income_category == 4 ~ 20499.5, # 16,000 to 24,999
                                            income_category == 5 ~ 29999.5, # 25,000 to 34,999
                                            income_category == 6 ~ 42499.5, # 35,000 to 49,999
                                            income_category == 7 ~ 62499.5, # 50,000 to 74,999
                                            income_category == 8 ~ 87499.5, # 75,000 to 99,999
                                            income_category == 9 ~ 149999.5, # 100,000 to 199,999
                                            income_category == 10 ~ 200000 # 200,000 and greater
                                  )) %>%
              # combine items for household size from baseline to yr 2 and yr 3+
              mutate(household_size = case_when(demo_roster_v2_refuse %in% c(777,999) ~ NA,
                                                demo_roster_v2_refuse_l %in% c(777,999) ~ NA,
                                        !is.na(demo_roster_v2) ~ demo_roster_v2,
                                        !is.na(demo_roster_v2_l) ~ demo_roster_v2_l
                                  )) %>%
              # for household size replace unreasonable values with NA
              mutate(household_size = ifelse(household_size %in% 
                                                c(-4, 0, 41, 43, 56, 60, 77, 110, 2300) , NA, household_size)) %>%
              # add year data was collected
              left_join(select(meta,c("src_subject_id","eventname","interview_date")),
                                    by=c("src_subject_id","eventname")) %>%
              mutate(year = as.integer(gsub("^.{1,6}","",interview_date))) %>%
              # add federal poverty line for given year and household size
              left_join(poverty_info,by=c("household_size","year")) %>%
              # calculate income to needs ratio
              mutate(income_to_needs = income_val/poverty_line)


## group all abcd data ####  
abcd_all <- demo %>%
              select(c("src_subject_id","eventname","demo_sex_v2",
                       "demo_gender_id_v2","demo_gender_id_v2_l")) %>%
              # combine items for gender from baseline to yr 2 and yr 3+
              mutate(gender_id = case_when(!is.na(demo_gender_id_v2) ~ demo_gender_id_v2,
                                        !is.na(demo_gender_id_v2_l) ~ demo_gender_id_v2_l
                                  )) %>%
              # for gender replace 777 and 999 with NA
              mutate(gender_id = ifelse(gender_id %in% c(777,999) , NA, gender_id)) %>%
              # add income to needs ratio
              left_join(income_df,by=c("src_subject_id","eventname")) %>%
              # add site and interview age
              left_join(select(meta,
                               c("src_subject_id","eventname",
                                 "site_id_l","interview_age")),
                        by=c("src_subject_id","eventname")) %>%
              rename(site = site_id_l) %>%
              # add cbcl scores
              left_join(select(cbcl,
                               c("src_subject_id","eventname",
                                 "cbcl_scr_syn_aggressive_t","cbcl_scr_syn_attention_t",
                                 "cbcl_scr_syn_anxdep_t","cbcl_scr_syn_external_t",
                                 "cbcl_scr_syn_internal_t","cbcl_scr_syn_rulebreak_t",
                                 "cbcl_scr_syn_social_t","cbcl_scr_syn_somatic_t",
                                 "cbcl_scr_syn_thought_t","cbcl_scr_syn_totprob_t",
                                 "cbcl_scr_syn_withdep_t")),
                        by=c("src_subject_id","eventname")) %>%
              # add ksads scores
              left_join(ksads,by=c("src_subject_id","eventname")) 

## group all prs data ####
prs_all <- prs_all_mhc %>%
              left_join(select(prs_one_mhc,c("SCORESUM","IID")),
                        by="IID") %>%
              rename(prs_all_mhc_val = SCORESUM.x,
                     prs_one_mhc_val = SCORESUM.y) %>%
              left_join(select(prs_no_mhc,c("SCORESUM","IID")),
                        by="IID") %>%
              rename(prs_no_mhc_val = SCORESUM) %>%
              select(c("IID","prs_all_mhc_val","prs_one_mhc_val","prs_no_mhc_val")) %>%
              rename(src_subject_id = IID)
prs_all$src_subject_id <- gsub("^.{1,10}","",prs_all$src_subject_id) #if remove first 10 char then = subject id as in abcd

## make categorical ancestry groups ####
afr_gp <- afr_gp %>% mutate(ancestry="Afr")
amadmix_gp <- amadmix_gp %>% mutate(ancestry="AmAdmix")
eur_gp <- eur_gp %>% mutate(ancestry="Eur")
ancestry_gp_all <- bind_rows(afr_gp,amadmix_gp,eur_gp) %>%
                      select("subjectkey","ancestry","V1","V2","V3","V4","V5","V6","V7","V8") %>%
                      rename(src_subject_id = subjectkey)

# rename grms so names are consistent with abcd names
#if remove first 10 char from rownames in grm then = subject id
rownames(all_grm) <- gsub("^.{1,10}","",rownames(all_grm)) 
colnames(all_grm) <- gsub("^.{1,10}","",colnames(all_grm))
rownames(afr_grm) <- gsub("^.{1,10}","",rownames(afr_grm))
colnames(afr_grm) <- gsub("^.{1,10}","",colnames(afr_grm))
rownames(amadmix_grm) <- gsub("^.{1,10}","",rownames(amadmix_grm))
colnames(amadmix_grm) <- gsub("^.{1,10}","",colnames(amadmix_grm))
rownames(eur_grm) <- gsub("^.{1,10}","",rownames(eur_grm))
colnames(eur_grm) <- gsub("^.{1,10}","",colnames(eur_grm))

### combine all data except grms ####
data_all <- abcd_all %>%
              left_join(prs_all, by="src_subject_id") %>%
              left_join(ancestry_gp_all, by="src_subject_id")

### remove subjects without ancestry information ####
data_all <- data_all %>% filter(!is.na(ancestry))

### Z-score all PRS based on ancestry ####
data_all <- data_all %>% 
          group_by(ancestry) %>%
          mutate(Zprs_all_mhc_val = as.numeric(scale(prs_all_mhc_val, scale=TRUE))) %>%
          mutate(Zprs_one_mhc_val = as.numeric(scale(prs_one_mhc_val, scale=TRUE))) %>%
          mutate(Zprs_no_mhc_val = as.numeric(scale(prs_no_mhc_val, scale=TRUE)))

```

### Separate data based on collection date

``` {separate data based on collection date, r}

baseline_data <- data_all %>% filter(eventname == "baseline_year_1_arm_1")
yr1_data <- data_all %>% filter(eventname == "1_year_follow_up_y_arm_1")
yr2_data <- data_all %>% filter(eventname == "2_year_follow_up_y_arm_1")
yr3_data <- data_all %>% filter(eventname == "3_year_follow_up_y_arm_1")
yr4_data <- data_all %>% filter(eventname == "4_year_follow_up_y_arm_1")

```


### Reorder data so matches grm

```{reorder data so matches grm, r}

### All ancestries ####
all_grm_for_yr <- all_grm[which(rownames(all_grm) %in% yr4_data$src_subject_id),]
all_grm_for_yr <- all_grm_for_yr[,which(colnames(all_grm_for_yr) %in% yr4_data$src_subject_id)]
row_indices_All <- match(yr4_data$src_subject_id,rownames(all_grm_for_yr)) 
all_grm_sparse_subsetted <- all_grm_for_yr[row_indices_All, row_indices_All]
all_yr4_data_reordered <- yr4_data[match(colnames(all_grm_sparse_subsetted),yr4_data$src_subject_id),]
all_yr4_data_reordered <- all_yr4_data_reordered %>% column_to_rownames(var="src_subject_id")

### African ancestry ####
afr_grm_for_yr <- afr_grm[which(rownames(afr_grm) %in% yr4_data$src_subject_id),]
afr_grm_for_yr <- afr_grm_for_yr[,which(colnames(afr_grm_for_yr) %in% yr4_data$src_subject_id)]
row_indices_All <- match(yr4_data$src_subject_id,rownames(afr_grm_for_yr)) 
afr_yr4_data <- yr4_data %>% filter(ancestry=="Afr")
row_indices_All <- match(afr_yr4_data$src_subject_id,rownames(afr_grm_for_yr))
afr_grm_sparse_subsetted <- afr_grm_for_yr[row_indices_All, row_indices_All]
afr_yr4_data_reordered <- afr_yr4_data[match(colnames(afr_grm_sparse_subsetted),
                                                       afr_yr4_data$src_subject_id),]
afr_yr4_data_reordered <- afr_yr4_data_reordered %>% column_to_rownames(var="src_subject_id")

### American admixed ancestry ####
amadmix_for_yr <- amadmix_grm[which(rownames(amadmix_grm) %in% yr4_data$src_subject_id),]
amadmix_for_yr <- amadmix_for_yr[,which(colnames(amadmix_for_yr) %in% yr4_data$src_subject_id)]
row_indices_All <- match(yr4_data$src_subject_id,rownames(amadmix_for_yr)) 
amadmix_yr4_data <- yr4_data %>% filter(ancestry=="AmAdmix")
row_indices_All <- match(amadmix_yr4_data$src_subject_id,rownames(amadmix_for_yr))
amadmix_grm_sparse_subsetted <- amadmix_for_yr[row_indices_All, row_indices_All]
amadmix_yr4_data_reordered <- amadmix_yr4_data[match(colnames(amadmix_grm_sparse_subsetted),
                                                               amadmix_yr4_data$src_subject_id),]
amadmix_yr4_data_reordered <- amadmix_yr4_data_reordered %>% column_to_rownames(var="src_subject_id")


### European ancestry ####
eur_grm_for_yr <- eur_grm[which(rownames(eur_grm) %in% yr4_data$src_subject_id),]
eur_grm_for_yr <- eur_grm_for_yr[,which(colnames(eur_grm_for_yr) %in% yr4_data$src_subject_id)]
eur_yr4_data <- yr4_data %>% filter(ancestry=="Eur")
row_indices_All <- match(eur_yr4_data$src_subject_id,rownames(eur_grm_for_yr))
eur_grm_sparse_subsetted <- eur_grm_for_yr[row_indices_All, row_indices_All]
eur_yr4_data_reordered <- eur_yr4_data[match(colnames(eur_grm_sparse_subsetted),
                                                       eur_yr4_data$src_subject_id),]
eur_yr4_data_reordered <- eur_yr4_data_reordered %>% column_to_rownames(var="src_subject_id")

```

### Run grm and ancestry pc for all CBCL outcomes at yr4

``` {run grm and ancestry pc for all cbcl outcomes, r}

## run lin reg for each cbcl outcome ####
cbcl_outcome_list <- c("cbcl_scr_syn_aggressive_t","cbcl_scr_syn_attention_t",
                  "cbcl_scr_syn_anxdep_t","cbcl_scr_syn_external_t",
                  "cbcl_scr_syn_internal_t","cbcl_scr_syn_rulebreak_t",
                  "cbcl_scr_syn_social_t","cbcl_scr_syn_somatic_t",
                  "cbcl_scr_syn_thought_t","cbcl_scr_syn_totprob_t",
                  "cbcl_scr_syn_withdep_t" )

lm_resid_cbcl_list <- list() 
for (outcome in cbcl_outcome_list) {
  lm_model <- fitNullModel(all_yr4_data_reordered, 
                           outcome = outcome, 
                           covars = c(paste0("V", 1:8)), 
                           cov.mat = all_grm_sparse_subsetted, 
                           verbose = TRUE)
  lm_resid_cbcl_list[[outcome]] <- lm_model$fit %>%
                              rownames_to_column("id") %>%
                              select(c(id,resid.conditional))
}

## make one data frame with residuals for all cbcl results
lm_all_cond_resid_cbcl_long <- imap_dfr(lm_resid_cbcl_list, ~mutate(.x, .id = .y))
lm_resid_cbcl <- lm_all_cond_resid_cbcl_long %>%
  pivot_wider(names_from = .id, values_from = resid.conditional)

```

### Run grm and ancestry pc regressions for KSADS outcomes at yr4

```{run grm and ancestry pc for all ksads outcomes, r}

## run lin reg for each ksads outcome ####

ksads_outcome_list <- c("adhd","gad","mdd","ptsd")

lm_resid_ksads_list <- list() # initialize a list to store results  
for (outcome in ksads_outcome_list) {
  lm_model <- fitNullModel(all_yr4_data_reordered, 
                           outcome = outcome, 
                           covars = c(paste0("V", 1:8)), 
                           cov.mat = all_grm_sparse_subsetted, 
                           verbose = TRUE,
                           family = "binomial")
  lm_resid_ksads_list[[outcome]] <- lm_model$fit %>%
                              rownames_to_column("id") %>%
                              select(c(id,resid.conditional))
}

## make one data frame with residuals for all ksads results
lm_all_cond_resid_ksads_long <- imap_dfr(lm_resid_ksads_list, ~mutate(.x, .id = .y))
lm_resid_ksads <- lm_all_cond_resid_ksads_long %>%
  pivot_wider(names_from = .id, values_from = resid.conditional)

```

### Run regression for PRS and covariates for CBCL outcomes at yr4

``` {run regression for prs and covariates for cbcl, r}

## subset data for regression, combine with residuals from last regression ####
yr4_reg_data <- yr4_data %>%
                select(c("src_subject_id","prs_all_mhc_val",
                         "demo_gender_id_v2_l",
                         "income_to_needs","site","interview_age",
                         "ancestry",
                         "cbcl_scr_syn_aggressive_t","cbcl_scr_syn_attention_t",
                         "cbcl_scr_syn_anxdep_t","cbcl_scr_syn_external_t",
                         "cbcl_scr_syn_internal_t","cbcl_scr_syn_rulebreak_t",
                         "cbcl_scr_syn_social_t","cbcl_scr_syn_somatic_t",
                         "cbcl_scr_syn_thought_t","cbcl_scr_syn_totprob_t",
                         "cbcl_scr_syn_withdep_t",
                         "adhd","gad","mdd","ptsd",
                         )) %>%
                rename(
                  id = src_subject_id,
                  gender = demo_gender_id_v2_l,
                  age = interview_age,
                  prs = prs_all_mhc_val,
                  raw_c_aggress = cbcl_scr_syn_aggressive_t,
                  raw_c_attn = cbcl_scr_syn_attention_t,
                  raw_c_anxdep = cbcl_scr_syn_anxdep_t,
                  raw_c_ext = cbcl_scr_syn_external_t,
                  raw_c_int = cbcl_scr_syn_internal_t,
                  raw_c_rule = cbcl_scr_syn_rulebreak_t,
                  raw_c_social = cbcl_scr_syn_social_t,
                  raw_c_somatic = cbcl_scr_syn_somatic_t,
                  raw_c_thought = cbcl_scr_syn_thought_t,
                  raw_c_total = cbcl_scr_syn_totprob_t,
                  raw_c_withdep = cbcl_scr_syn_withdep_t,
                  raw_k_adhd = adhd,
                  raw_k_gad = gad,
                  raw_k_mdd = mdd,
                  raw_k_ptsd = ptsd
                ) %>%
                mutate(gender = case_when(gender == 1 ~ "cism",
                                          gender == 2 ~ "cisf",
                                          gender == 3 ~ "gnc", #trans m
                                          gender == 4 ~ "gnc", #trans f
                                          gender == 5 ~ "gnc", #genderqueer
                                          gender == 6 ~ "gnc", #other
                                          gender == 777 ~ NA,
                                          gender == 999 ~ NA,
        
                )) %>%
                left_join(lm_resid_cbcl,by="id") %>%
                left_join(lm_resid_ksads,by="id") %>%
                rename(
                        res_c_aggress = cbcl_scr_syn_aggressive_t,
                        res_c_attn = cbcl_scr_syn_attention_t,
                        res_c_anxdep = cbcl_scr_syn_anxdep_t,
                        res_c_ext = cbcl_scr_syn_external_t,
                        res_c_int = cbcl_scr_syn_internal_t,
                        res_c_rule = cbcl_scr_syn_rulebreak_t,
                        res_c_social = cbcl_scr_syn_social_t,
                        res_c_somatic = cbcl_scr_syn_somatic_t,
                        res_c_thought = cbcl_scr_syn_thought_t,
                        res_c_total = cbcl_scr_syn_totprob_t,
                        res_c_withdep = cbcl_scr_syn_withdep_t,
                        res_k_adhd = adhd,
                        res_k_gad = gad,
                        res_k_mdd = mdd,
                        res_k_ptsd = ptsd
                ) %>%
        
### dummy code, effect code, and cluster mean center categorical variables ####
## dummy
# gender - cismale: gen_dum_cisf = 0, gen_dum_gnc = 0
# gender - cisfemale: gen_dum_cisf = 1, gen_dum_gnc = 0
# gender - gnc/other: gen_dum_cisf = 0, gen_dum_gnc = 1
# ancestry - amadmix: anc_dum_afr = 0, anc_dum_eur = 0
# ancestry - afr: anc_dum_afr = 1, anc_dum_eur = 0
# ancestry - eur: anc_dum_afr = 0, anc_dum_eur = 1
## effect
# gender - cismale: gen_eff_cisf = -1, gen_eff_gnc = -1
# gender - cisfemale: gen_eff_cisf = 1, gen_eff_gnc = 0
# gender - gnc/other: gen_eff_cisf = 0, gen_eff_gnc = 1
# ancestry - amadmix: anc_eff_afr = -1, anc_eff_eur = -1
# ancestry - afr: anc_eff_afr = 1, anc_eff_eur = 0
# ancestry - eur: anc_eff_afr = 0, anc_eff_eur = 1

                # dummy coding
                mutate(gen_dum_cisf = case_when(gender == "cism" ~ 0,
                                                gender == "cisf" ~ 1,
                                                gender == "gnc" ~ 0)) %>%
                mutate(gen_dum_gnc = case_when(gender == "cism" ~ 0,
                                                gender == "cisf" ~ 0,
                                                gender == "gnc" ~ 1)) %>%
                mutate(anc_dum_afr = case_when(ancestry == "AmAdmix" ~ 0,
                                               ancestry == "Afr" ~ 1,
                                               ancestry == "Eur" ~ 0)) %>%
                mutate(anc_dum_eur = case_when(ancestry == "AmAdmix" ~ 0,
                                               ancestry == "Afr" ~ 0,
                                               ancestry == "Eur" ~ 1)) %>%
                # effect coding
                mutate(gen_eff_cisf = case_when(gender == "cism" ~ -1,
                                                gender == "cisf" ~ 1,
                                                gender == "gnc" ~ 0)) %>%
                mutate(gen_eff_gnc = case_when(gender == "cism" ~ -1,
                                                gender == "cisf" ~ 0,
                                                gender == "gnc" ~ 1)) %>%
                # mutate(anc_eff_afr = as.numeric(car::recode(anc_dum_afr, "0=-1;1=1"))) %>% 
                mutate(anc_eff_afr = case_when(ancestry == "AmAdmix" ~ -1,
                                               ancestry == "Afr" ~ 1,
                                               ancestry == "Eur" ~ 0)) %>%
                mutate(anc_eff_eur = case_when(ancestry == "AmAdmix" ~ -1,
                                               ancestry == "Afr" ~ 0,
                                               ancestry == "Eur" ~ 1)) %>%
                # cluster mean center categorical predictors
                mutate(gen_cmc_cisf = as.numeric(center(gen_eff_cisf, 
                                     type="CWC", cluster = site))) %>%
                mutate(gen_cmc_gnc = as.numeric(center(gen_eff_gnc, 
                                     type="CWC", cluster = site))) %>%
                mutate(anc_cmc_afr = as.numeric(center(anc_eff_afr, 
                                     type="CWC", cluster = site))) %>%
                mutate(anc_cmc_eur = as.numeric(center(anc_eff_eur, 
                                     type="CWC", cluster = site))) %>%
                # cluster mean center continuous predictors
                mutate(cmc_prs = as.numeric(center(prs,type="CWC",cluster=site))) %>%
                mutate(cmc_age = as.numeric(center(age,type="CWC",cluster=site))) %>%
                mutate(cmc_income_to_needs = as.numeric(center(income_to_needs,
                                                        type="CWC",cluster=site))) %>%
                # Z score continuous predictors ()
                mutate(zcmc_prs = cmc_prs) %>%
                mutate(zcmc_age = as.numeric(scale(cmc_age, scale=TRUE))) %>%
                mutate(zcmc_income = as.numeric(scale(cmc_income_to_needs, scale=TRUE))) %>%

                #reorder columns so easier to work with
                select(id,site,prs,age,income_to_needs,gender,ancestry,
                       zcmc_prs,zcmc_age,zcmc_income,
                       gen_dum_cisf,gen_dum_gnc,
                       gen_eff_cisf,gen_eff_gnc,
                       gen_cmc_cisf,gen_cmc_gnc,
                       anc_dum_afr,anc_dum_eur,
                       anc_eff_afr,anc_eff_eur,
                       anc_cmc_afr,anc_cmc_eur,
                       res_c_total,res_c_ext,res_c_int,
                       res_c_aggress,res_c_attn,res_c_anxdep,res_c_withdep,
                       res_c_rule,res_c_social,res_c_somatic,res_c_thought,
                       res_k_adhd,res_k_gad,res_k_mdd,res_k_ptsd,
                       raw_c_total,raw_c_ext,raw_c_int,
                       raw_c_aggress,raw_c_attn,raw_c_anxdep,raw_c_withdep,
                       raw_c_rule,raw_c_social,raw_c_somatic,raw_c_thought,
                       raw_k_adhd,raw_k_gad,raw_k_mdd,raw_k_ptsd
                       )

```

``` {cbcl regressions, icc for x variables,r}

### Obtaining ICCs for L1 Predictors (Intercept-Only Model for X) ----
income_to_needs_M0 <- lmer(income_to_needs ~ (1|site), data=yr4_reg_data, REML=FALSE)
summary(income_to_needs_M0)
variances = as.data.frame(VarCorr(income_to_needs_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_income_to_needs <- cluster_var/(cluster_var + resid_var)
ICC_income_to_needs #15% of the variance in income-to-needs is explained by site

age_M0 <- lmer(age ~ (1|site), data=yr4_reg_data, REML=FALSE)
summary(age_M0)
variances = as.data.frame(VarCorr(age_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_age <- cluster_var/(cluster_var + resid_var)
ICC_age #11% of the variance in age is explained by site

prs_M0 <- lmer(prs ~ (1|site), data=yr4_reg_data, REML=FALSE)
summary(prs_M0)
variances = as.data.frame(VarCorr(prs_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_prs <- cluster_var/(cluster_var + resid_var)
ICC_prs #1% of the variance in PRS is explained by site
```

``` {cbcl regressions, total problems,r}

## Total problems score ----
### Intercept-Only Model Estimation (for Y) ----
cbcl_total_M0 <- lmer(res_c_total ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(cbcl_total_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(cbcl_total_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0.3% of the variance in total problems is explained by site

### Random Intercept, Fixed Slopes without interactions ----
cbcl_total_M1a <- lmer(res_c_total ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_total_M1a)

### Random Intercept, Fixed Slopes with interactions ----
cbcl_total_M1b <- lmer(res_c_total ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_total_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
cbcl_total_M2a <- lmer(res_c_total ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site), #don't have enough to add more variables to random slope
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_total_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
cbcl_total_M2b <- lmer(res_c_total ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site), #don't have enough to add more variables to random slope
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_total_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
cbcl_total_M2c <- lmer(res_c_total ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1+zcmc_prs+zcmc_income+zcmc_age+
                        gen_cmc_cisf + gen_cmc_gnc |site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_total_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
cbcl_total_M2d <- lmer(res_c_total ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1+zcmc_prs+zcmc_income+zcmc_age+
                        gen_cmc_cisf + gen_cmc_gnc |site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_total_M2d)

### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(cbcl_total_M1a,cbcl_total_M1b,test="Chisq")  #1a is better
anova(cbcl_total_M1a,cbcl_total_M2a,test="Chisq") #1a is better
anova(cbcl_total_M1a,cbcl_total_M2b,test="Chisq") #1a is better
anova(cbcl_total_M1a,cbcl_total_M2c,test="Chisq") #1a is better
anova(cbcl_total_M1b,cbcl_total_M2b,test="Chisq") #1b is better than 2b
anova(cbcl_total_M1b,cbcl_total_M2d,test="Chisq") #1b is better than 2d
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope




```

``` {cbcl regressions, externalizing,r}

## Externalizing problems score ----
### Intercept-Only Model Estimation (for Y) ----
cbcl_ext_M0 <- lmer(res_c_ext ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(cbcl_ext_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(cbcl_ext_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0.2% of the variance in Externalizing problems is explained by site

### Random Intercept, Fixed Slopes without interactions ----
cbcl_ext_M1a <- lmer(res_c_ext ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_ext_M1a)

### Random Intercept, Fixed Slopes with interactions ----
cbcl_ext_M1b <- lmer(res_c_ext ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_ext_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
cbcl_ext_M2a <- lmer(res_c_ext ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_ext_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
cbcl_ext_M2b <- lmer(res_c_ext ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_ext_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
# failed to converge with either optimizer
# cbcl_ext_M2c <- lmer(res_c_ext ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# 
# summary(cbcl_ext_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# cbcl_ext_M2d <- lmer(res_c_ext ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_ext_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(cbcl_ext_M1a,cbcl_ext_M1b,test="Chisq")  #1a is better
anova(cbcl_ext_M1a,cbcl_ext_M2a,test="Chisq") #1a is better
anova(cbcl_ext_M1a,cbcl_ext_M2b,test="Chisq") #1a is better
anova(cbcl_ext_M1b,cbcl_ext_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```


``` {cbcl regressions, internalizing,r}

## Internalizing problems score ----
### Intercept-Only Model Estimation (for Y) ----
cbcl_int_M0 <- lmer(res_c_int ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(cbcl_int_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(cbcl_int_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0.2% of the variance in internalizing problems is explained by site

### Random Intercept, Fixed Slopes without interactions ----
cbcl_int_M1a <- lmer(res_c_int ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_int_M1a)

### Random Intercept, Fixed Slopes with interactions ----
cbcl_int_M1b <- lmer(res_c_int ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_int_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
cbcl_int_M2a <- lmer(res_c_int ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_int_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
cbcl_int_M2b <- lmer(res_c_int ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_int_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
cbcl_int_M2c <- lmer(res_c_int ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1+zcmc_prs+zcmc_income+zcmc_age+
                        gen_cmc_cisf + gen_cmc_gnc |site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_int_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# cbcl_int_M2d <- lmer(res_c_int ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_int_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(cbcl_int_M1a,cbcl_int_M1b,test="Chisq")  #1a is better
anova(cbcl_int_M1a,cbcl_int_M2a,test="Chisq") #1a is better
anova(cbcl_int_M1a,cbcl_int_M2b,test="Chisq") #1a is better
anova(cbcl_int_M1a,cbcl_int_M2c,test="Chisq") #1a is better
anova(cbcl_int_M1b,cbcl_int_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```


``` {cbcl regressions, aggressive,r}

## Aggressive problems score ----
### Intercept-Only Model Estimation (for Y) ----
cbcl_aggress_M0 <- lmer(res_c_aggress ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(cbcl_aggress_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(cbcl_aggress_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0.1% of the variance in aggression problems is explained by site

### Random Intercept, Fixed Slopes without interactions ----
cbcl_aggress_M1a <- lmer(res_c_aggress ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_aggress_M1a)

### Random Intercept, Fixed Slopes with interactions ----
cbcl_aggress_M1b <- lmer(res_c_aggress ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_aggress_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
cbcl_aggress_M2a <- lmer(res_c_aggress ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_aggress_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
cbcl_aggress_M2b <- lmer(res_c_aggress ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_aggress_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
cbcl_aggress_M2c <- lmer(res_c_aggress ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1+zcmc_prs+zcmc_income+zcmc_age+
                        gen_cmc_cisf + gen_cmc_gnc |site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
                    # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))

summary(cbcl_aggress_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# cbcl_aggress_M2d <- lmer(res_c_aggress ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_aggress_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(cbcl_aggress_M1a,cbcl_aggress_M1b,test="Chisq")  #1a is better
anova(cbcl_aggress_M1a,cbcl_aggress_M2a,test="Chisq") #1a is better
anova(cbcl_aggress_M1a,cbcl_aggress_M2b,test="Chisq") #1a is better
anova(cbcl_aggress_M1a,cbcl_aggress_M2c,test="Chisq") #1a is better
anova(cbcl_aggress_M1b,cbcl_aggress_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```


``` {cbcl regressions, attention,r}

## Attention problems score ----
### Intercept-Only Model Estimation (for Y) ----
cbcl_attn_M0 <- lmer(res_c_attn ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(cbcl_attn_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(cbcl_attn_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0.1% of the variance in attention problems is explained by site

### Random Intercept, Fixed Slopes without interactions ----
cbcl_attn_M1a <- lmer(res_c_attn ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_attn_M1a)

### Random Intercept, Fixed Slopes with interactions ----
cbcl_attn_M1b <- lmer(res_c_attn ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_attn_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
cbcl_attn_M2a <- lmer(res_c_attn ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_attn_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
cbcl_attn_M2b <- lmer(res_c_attn ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_attn_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
# failed to converge with either optimizer
# cbcl_attn_M2c <- lmer(res_c_attn ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_attn_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# cbcl_attn_M2d <- lmer(res_c_attn ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_attn_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(cbcl_attn_M1a,cbcl_attn_M1b,test="Chisq")  #1a is better
anova(cbcl_attn_M1a,cbcl_attn_M2a,test="Chisq") #1a is better
anova(cbcl_attn_M1a,cbcl_attn_M2b,test="Chisq") #1a is better
anova(cbcl_attn_M1b,cbcl_attn_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```


``` {cbcl regressions, anxious/depressed,r}

## Anxious/depressed problems score ----
### Intercept-Only Model Estimation (for Y) ----
cbcl_anxdep_M0 <- lmer(res_c_anxdep ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(cbcl_anxdep_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(cbcl_anxdep_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0.01% of the variance in anxious/depressed problems is explained by site

### Random Intercept, Fixed Slopes without interactions ----
cbcl_anxdep_M1a <- lmer(res_c_anxdep ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_anxdep_M1a)

### Random Intercept, Fixed Slopes with interactions ----
cbcl_anxdep_M1b <- lmer(res_c_anxdep ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_anxdep_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
cbcl_anxdep_M2a <- lmer(res_c_anxdep ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_anxdep_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
cbcl_anxdep_M2b <- lmer(res_c_anxdep ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_anxdep_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
# failed to converge with either optimizer
# cbcl_anxdep_M2c <- lmer(res_c_anxdep ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# 
# summary(cbcl_anxdep_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# cbcl_anxdep_M2d <- lmer(res_c_anxdep ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_anxdep_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(cbcl_anxdep_M1a,cbcl_anxdep_M1b,test="Chisq")  #1a is better
anova(cbcl_anxdep_M1a,cbcl_anxdep_M2a,test="Chisq") #1a is better
anova(cbcl_anxdep_M1a,cbcl_anxdep_M2b,test="Chisq") #1a is better
anova(cbcl_anxdep_M1b,cbcl_anxdep_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```


``` {cbcl regressions, withdrawn/depressed,r}

## Withdrawn/depressed problems score ----
### Intercept-Only Model Estimation (for Y) ----
cbcl_withdep_M0 <- lmer(res_c_withdep ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(cbcl_withdep_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(cbcl_withdep_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0.3% of the variance in withdrawn/depressed problems is explained by site

### Random Intercept, Fixed Slopes without interactions ----
cbcl_withdep_M1a <- lmer(res_c_withdep ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_withdep_M1a)

### Random Intercept, Fixed Slopes with interactions ----
cbcl_withdep_M1b <- lmer(res_c_withdep ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_withdep_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
cbcl_withdep_M2a <- lmer(res_c_withdep ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_withdep_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
cbcl_withdep_M2b <- lmer(res_c_withdep ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_withdep_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
# failed to converge with either optimizer
# cbcl_withdep_M2c <- lmer(res_c_withdep ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_withdep_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
cbcl_withdep_M2d <- lmer(res_c_withdep ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1+zcmc_prs+zcmc_income+zcmc_age+
                        gen_cmc_cisf + gen_cmc_gnc |site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
                    # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_withdep_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(cbcl_withdep_M1a,cbcl_withdep_M1b,test="Chisq")  #1a is better
anova(cbcl_withdep_M1a,cbcl_withdep_M2a,test="Chisq") #1a is better
anova(cbcl_withdep_M1a,cbcl_withdep_M2b,test="Chisq") #1a is better
anova(cbcl_withdep_M1a,cbcl_withdep_M2d,test="Chisq") #1a is better
anova(cbcl_withdep_M1b,cbcl_withdep_M2b,test="Chisq") #1b is better
anova(cbcl_withdep_M1b,cbcl_withdep_M2d,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```


``` {cbcl regressions, rulebreaking,r}

## Rule-breaking problems score ----
### Intercept-Only Model Estimation (for Y) ----
cbcl_rule_M0 <- lmer(res_c_rule ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(cbcl_rule_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(cbcl_rule_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0.04% of the variance in rule-breaking problems is explained by site

### Random Intercept, Fixed Slopes without interactions ----
cbcl_rule_M1a <- lmer(res_c_rule ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_rule_M1a)

### Random Intercept, Fixed Slopes with interactions ----
cbcl_rule_M1b <- lmer(res_c_rule ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_rule_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
cbcl_rule_M2a <- lmer(res_c_rule ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_rule_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
cbcl_rule_M2b <- lmer(res_c_rule ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_rule_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
# failed to converge with either optimizer
# cbcl_rule_M2c <- lmer(res_c_rule ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_rule_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# cbcl_rule_M2d <- lmer(res_c_rule ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_rule_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(cbcl_rule_M1a,cbcl_rule_M1b,test="Chisq")  #1a is better
anova(cbcl_rule_M1a,cbcl_rule_M2a,test="Chisq") #1a is better
anova(cbcl_rule_M1a,cbcl_rule_M2b,test="Chisq") #1a is better
anova(cbcl_rule_M1b,cbcl_rule_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```


``` {cbcl regressions, social,r}

## Social problems score ----
### Intercept-Only Model Estimation (for Y) ----
cbcl_social_M0 <- lmer(res_c_social ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(cbcl_social_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(cbcl_social_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0% of the variance in social problems is explained by site

### Random Intercept, Fixed Slopes without interactions ----
cbcl_social_M1a <- lmer(res_c_social ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_social_M1a)

### Random Intercept, Fixed Slopes with interactions ----
cbcl_social_M1b <- lmer(res_c_social ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_social_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
cbcl_social_M2a <- lmer(res_c_social ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_social_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
cbcl_social_M2b <- lmer(res_c_social ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_social_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
# failed to converge with either optimizer
# cbcl_social_M2c <- lmer(res_c_social ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_social_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# cbcl_social_M2d <- lmer(res_c_social ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_social_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(cbcl_social_M1a,cbcl_social_M1b,test="Chisq")  #1a is better
anova(cbcl_social_M1a,cbcl_social_M2a,test="Chisq") #1a is better
anova(cbcl_social_M1a,cbcl_social_M2b,test="Chisq") #1a is better
anova(cbcl_social_M1b,cbcl_social_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```


``` {cbcl regressions, somatic,r}

## Somatic problems score ----
### Intercept-Only Model Estimation (for Y) ----
cbcl_somatic_M0 <- lmer(res_c_somatic ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(cbcl_somatic_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(cbcl_somatic_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0.4% of the variance in somatic problems is explained by site

### Random Intercept, Fixed Slopes without interactions ----
cbcl_somatic_M1a <- lmer(res_c_somatic ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_somatic_M1a)

### Random Intercept, Fixed Slopes with interactions ----
cbcl_somatic_M1b <- lmer(res_c_somatic ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_somatic_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
cbcl_somatic_M2a <- lmer(res_c_somatic ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_somatic_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
cbcl_somatic_M2b <- lmer(res_c_somatic ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_somatic_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
# failed to converge with either optimizer
# cbcl_somatic_M2c <- lmer(res_c_somatic ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_somatic_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# cbcl_somatic_M2d <- lmer(res_c_somatic ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_somatic_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(cbcl_somatic_M1a,cbcl_somatic_M1b,test="Chisq")  #1a is better
anova(cbcl_somatic_M1a,cbcl_somatic_M2a,test="Chisq") #1a is better
anova(cbcl_somatic_M1a,cbcl_somatic_M2b,test="Chisq") #1a is better
anova(cbcl_somatic_M1b,cbcl_somatic_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```


``` {cbcl regressions, thought,r}

## Thought problems score ----
### Intercept-Only Model Estimation (for Y) ----
cbcl_thought_M0 <- lmer(res_c_thought ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(cbcl_thought_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(cbcl_thought_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0% of the variance in thought problems is explained by site

### Random Intercept, Fixed Slopes without interactions ----
cbcl_thought_M1a <- lmer(res_c_thought ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_thought_M1a)

### Random Intercept, Fixed Slopes with interactions ----
cbcl_thought_M1b <- lmer(res_c_thought ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(cbcl_thought_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
cbcl_thought_M2a <- lmer(res_c_thought ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_thought_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
cbcl_thought_M2b <- lmer(res_c_thought ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(cbcl_thought_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
# failed to converge with either optimizer
# cbcl_thought_M2c <- lmer(res_c_thought ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_thought_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# cbcl_thought_M2d <- lmer(res_c_thought ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(cbcl_thought_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(cbcl_thought_M1a,cbcl_thought_M1b,test="Chisq")  #1b is better
anova(cbcl_thought_M1b,cbcl_thought_M2a,test="Chisq") #1b is better
anova(cbcl_thought_M1b,cbcl_thought_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope with interactions

```


``` {ksads regressions, adhd,r}

## ADHD ----
### Intercept-Only Model Estimation (for Y) ----
ksads_adhd_M0 <- lmer(res_k_adhd ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(ksads_adhd_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(ksads_adhd_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0% of the variance in adhd diagnoses is explained by site

### Random Intercept, Fixed Slopes without interactions ----
ksads_adhd_M1a <- lmer(res_k_adhd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(ksads_adhd_M1a)

### Random Intercept, Fixed Slopes with interactions ----
ksads_adhd_M1b <- lmer(res_k_adhd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(ksads_adhd_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
ksads_adhd_M2a <- lmer(res_k_adhd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(ksads_adhd_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
ksads_adhd_M2b <- lmer(res_k_adhd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(ksads_adhd_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
ksads_adhd_M2c <- lmer(res_k_adhd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1+zcmc_prs+zcmc_income+zcmc_age+
                        gen_cmc_cisf + gen_cmc_gnc |site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
                    # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
summary(ksads_adhd_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
ksads_adhd_M2d <- lmer(res_k_adhd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1+zcmc_prs+zcmc_income+zcmc_age+
                        gen_cmc_cisf + gen_cmc_gnc |site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
                    # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
summary(ksads_adhd_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(ksads_adhd_M1a,ksads_adhd_M1b,test="Chisq")  #1a  is better
anova(ksads_adhd_M1a,ksads_adhd_M2a,test="Chisq") #1a is better
anova(ksads_adhd_M1a,ksads_adhd_M2b,test="Chisq") #1a is better
anova(ksads_adhd_M1a,ksads_adhd_M2c,test="Chisq") #1a is better
anova(ksads_adhd_M1a,ksads_adhd_M2d,test="Chisq") #1a is better
anova(ksads_adhd_M1b,ksads_adhd_M2b,test="Chisq") #1b is better
anova(ksads_adhd_M1b,ksads_adhd_M2d,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```

``` {ksads regressions, gad,r}

## GAD ----
### Intercept-Only Model Estimation (for Y) ----
ksads_gad_M0 <- lmer(res_k_gad ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(ksads_gad_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(ksads_gad_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0% of the variance in gad diagnoses is explained by site

### Random Intercept, Fixed Slopes without interactions ----
ksads_gad_M1a <- lmer(res_k_gad ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(ksads_gad_M1a)

### Random Intercept, Fixed Slopes with interactions ----
ksads_gad_M1b <- lmer(res_k_gad ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(ksads_gad_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
ksads_gad_M2a <- lmer(res_k_gad ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(ksads_gad_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
ksads_gad_M2b <- lmer(res_k_gad ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(ksads_gad_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
# failed to converge with either optimizer
# ksads_gad_M2c <- lmer(res_k_gad ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(ksads_gad_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# ksads_gad_M2d <- lmer(res_k_gad ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(ksads_gad_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(ksads_gad_M1a,ksads_gad_M1b,test="Chisq")  #1a  is better
anova(ksads_gad_M1a,ksads_gad_M2a,test="Chisq") #1a is better
anova(ksads_gad_M1a,ksads_gad_M2b,test="Chisq") #1a is better
anova(ksads_gad_M1b,ksads_gad_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```


``` {ksads regressions, mdd,r}

## MDD ----
### Intercept-Only Model Estimation (for Y) ----
ksads_mdd_M0 <- lmer(res_k_mdd ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(ksads_mdd_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(ksads_mdd_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0.2% of the variance in mdd diagnoses is explained by site

### Random Intercept, Fixed Slopes without interactions ----
ksads_mdd_M1a <- lmer(res_k_mdd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(ksads_mdd_M1a)

### Random Intercept, Fixed Slopes with interactions ----
ksads_mdd_M1b <- lmer(res_k_mdd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(ksads_mdd_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
ksads_mdd_M2a <- lmer(res_k_mdd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(ksads_mdd_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
ksads_mdd_M2b <- lmer(res_k_mdd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(ksads_mdd_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
# failed to converge with either optimizer
# ksads_mdd_M2c <- lmer(res_k_mdd ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(ksads_mdd_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# ksads_mdd_M2d <- lmer(res_k_mdd ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(ksads_mdd_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(ksads_mdd_M1a,ksads_mdd_M1b,test="Chisq")  #1a  is better
anova(ksads_mdd_M1a,ksads_mdd_M2a,test="Chisq") #1a is better
anova(ksads_mdd_M1a,ksads_mdd_M2b,test="Chisq") #1a is better
anova(ksads_mdd_M1b,ksads_mdd_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```

``` {ksads regressions, ptsd,r}

## PTSD ----
### Intercept-Only Model Estimation (for Y) ----
ksads_ptsd_M0 <- lmer(res_k_ptsd ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(ksads_ptsd_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(ksads_ptsd_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0% of the variance in ptsd diagnoses is explained by site

### Random Intercept, Fixed Slopes without interactions ----
ksads_ptsd_M1a <- lmer(res_k_ptsd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(ksads_ptsd_M1a)

### Random Intercept, Fixed Slopes with interactions ----
ksads_ptsd_M1b <- lmer(res_k_ptsd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(ksads_ptsd_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
ksads_ptsd_M2a <- lmer(res_k_ptsd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(ksads_ptsd_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
ksads_ptsd_M2b <- lmer(res_k_ptsd ~ zcmc_prs + zcmc_age + zcmc_income +
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_income|site)+(0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(ksads_ptsd_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
# failed to converge with either optimizer
# ksads_ptsd_M2c <- lmer(res_k_ptsd ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(ksads_ptsd_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# ksads_ptsd_M2d <- lmer(res_k_ptsd ~ zcmc_prs + zcmc_age + zcmc_income +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*zcmc_income +
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_income+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(ksads_ptsd_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(ksads_ptsd_M1a,ksads_ptsd_M1b,test="Chisq")  #1a  is better
anova(ksads_ptsd_M1a,ksads_ptsd_M2a,test="Chisq") #1a is better
anova(ksads_ptsd_M1a,ksads_ptsd_M2b,test="Chisq") #1a is better
anova(ksads_ptsd_M1b,ksads_ptsd_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope without interactions
# if want to include interactions, use fixed slope

```


``` {effect of prs on covariates regressions, r}

## Income-to-needs ----
### Intercept-Only Model Estimation (for Y) ----
zcmc_income_M0 <- lmer(zcmc_income ~ 1 + (1|site), data=yr4_reg_data, REML=FALSE)
summary(zcmc_income_M0)

### computing the ICC for Y using variance components ----
variances = as.data.frame(VarCorr(zcmc_income_M0))
cluster_var = variances[1,'vcov']
resid_var = variances[2,'vcov']
ICC_Y2 <- cluster_var/(cluster_var + resid_var)
ICC_Y2 # 0% of the variance in income-to-needs is explained by site, which is
       # good news because income-to-needs was cluster mean centered by site

### Random Intercept, Fixed Slopes without interactions ----
zcmc_income_M1a <- lmer(zcmc_income ~ zcmc_prs + zcmc_age + 
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(zcmc_income_M1a)

### Random Intercept, Fixed Slopes with interactions ----
zcmc_income_M1b <- lmer(zcmc_income ~ zcmc_prs + zcmc_age + 
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
                      (1|site),
                    data=yr4_reg_data, REML=FALSE)
summary(zcmc_income_M1b)

### Random Intercept, random slopes, random effects uncorrelated without interactions ----
zcmc_income_M2a <- lmer(zcmc_income ~ zcmc_prs + zcmc_age + 
                        gen_cmc_cisf + gen_cmc_gnc +
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(zcmc_income_M2a)

### Random Intercept, random slopes, random effects uncorrelated with interactions ----
zcmc_income_M2b <- lmer(zcmc_income ~ zcmc_prs + zcmc_age + 
                        gen_cmc_cisf + gen_cmc_gnc +
                        zcmc_prs*zcmc_age + zcmc_prs*
                        zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc + 
                      (1|site)+(0+zcmc_prs|site)+
                      (0+zcmc_age|site)+
                      (0+gen_cmc_cisf|site)+(0+gen_cmc_gnc|site),
                    data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
summary(zcmc_income_M2b)

### Random Intercept, random slopes, random effects free to correlate without interactions ----
# failed to converge with either optimizer
# zcmc_income_M2c <- lmer(zcmc_income ~ zcmc_prs + zcmc_age +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(zcmc_income_M2c)

### Random Intercept, random slopes, random effects free to correlate with interactions ----
# failed to converge with either optimizer
# zcmc_income_M2d <- lmer(zcmc_income ~ zcmc_prs + zcmc_age +
#                         gen_cmc_cisf + gen_cmc_gnc +
#                         zcmc_prs*zcmc_age + zcmc_prs*
#                         zcmc_prs*gen_cmc_cisf + zcmc_prs*gen_cmc_gnc +
#                       (1+zcmc_prs+zcmc_age+
#                         gen_cmc_cisf + gen_cmc_gnc |site),
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="bobyqa"))
#                     # data=yr4_reg_data, REML=FALSE,control=lmerControl(optimizer="Nelder_Mead"))
# summary(zcmc_income_M2d)


### Model Comparisons of AIC/BIC fit indices and Likelihood Ratio Test (LRT) ----
anova(zcmc_income_M1a,zcmc_income_M1b,test="Chisq")  #1b is better
anova(zcmc_income_M1b,zcmc_income_M2a,test="Chisq") #1b is better
anova(zcmc_income_M1b,zcmc_income_M2b,test="Chisq") #1b is better
# best fitting model is fixed slope with interactions

```










```{r}

ggplot(aes(x=prs_one_mhc_val,y=cbcl_scr_syn_aggressive_t),data=eur_yr4_data_reordered) +
  geom_point(color="gray") +
  geom_smooth() +
  theme_bw()


ggplot(aes(x=prs_all_mhc_val,y=cbcl_scr_syn_anxdep_t),data=yr4_data_reordered) +
  geom_point(color="gray") +
  geom_smooth() +
  theme_bw()

ggplot(aes(x=prs_no_mhc_val,y=cbcl_scr_syn_external_t),data=yr4_data_reordered) +
  geom_point(color="gray") +
  geom_smooth() +
  theme_bw()

ggplot(aes(x=prs_all_mhc_val,y=cbcl_scr_syn_internal_t),data=eur_yr4_data_reordered) +
  geom_point(color="gray") +
  geom_smooth() +
  theme_bw()

ggplot(aes(x=prs_one_mhc_val,y=cbcl_scr_syn_rulebreak_t),data=eur_yr4_data_reordered) +
  geom_point(color="gray") +
  geom_smooth() +
  theme_bw()

ggplot(aes(x=prs_one_mhc_val,y=cbcl_scr_syn_somatic_t),data=amadmix_yr4_data_reordered) +
  geom_point(color="gray") +
  geom_smooth() +
  theme_bw()

ggplot(aes(x=prs_all_mhc_val,y=cbcl_scr_syn_thought_t),data=yr4_data_reordered) +
  geom_point(color="gray") +
  geom_smooth() +
  theme_bw()

ggplot(aes(x=prs_all_mhc_val,y=cbcl_scr_syn_totprob_t),data=eur_yr4_data_reordered) +
  geom_point(color="gray") +
  geom_smooth() +
  theme_bw()

ggplot(aes(x=prs_one_mhc_val,y=cbcl_scr_syn_withdep_t),data=eur_yr4_data_reordered) +
  geom_point(color="gray") +
  geom_smooth() +
  theme_bw()



```